### ISSUE TITLE
Cannot get data for certain strain

### ISSUE THREAD

**Issue by elena-krismer** [JKoblitz/bacdive-api#2]
I am retrieving data from multiple strains.
However, when I am trying to retrieve data from Bacteroides fragilis  BF8 (159984), I get no results even though the information is present.
 https://bacdive.dsmz.de/strain/159984
Neither using the id nor the genome_accession number give me any results:
<img width="455" alt="Screenshot 2022-06-14 at 14 15 01" src="https://user-images.githubusercontent.com/70535771/173575409-a4001d77-773c-49b7-a4a3-9feebe14c14a.png">
Thanks a lot!

**Comment by JKoblitz** [comment]
Hey @elena-krismer, sorry for getting back to you so late. 

I had a look into this issue and it turned out there was a problem with the BacDive API itself. However, my colleague fixed the issue, so it should work now properly. I also tested it and did get a proper response. 

Please come back to me if you face any more problems.

Cheers, Julia
