### ISSUE TITLE
Fuzy search?

### ISSUE THREAD

**Issue by adnanoner** [JKoblitz/bacdive-api#3]
Hi there,

Great tool :). Is there a way to do a fuzzy search? For example: client.search(taxonomy='methyl') to find various methylotrophs.

Thanks in advance!

**Comment by JKoblitz** [comment]
Hey @adnanoner, thank you for the question. Unfortunately, this is not possible at the moment, since the API itself does not support fuzzy searches. 

However, you might use the excellent [advanced search of BacDive](https://bacdive.dsmz.de/advsearch?fg%5B1%5D%5Bgc%5D=OR&fg%5B1%5D%5Bfl%5D%5B1%5D%5Bfd%5D=Genus&fg%5B1%5D%5Bfl%5D%5B1%5D%5Bfo%5D=contains&fg%5B1%5D%5Bfl%5D%5B1%5D%5Bfv%5D=Methyl&fg%5B1%5D%5Bfl%5D%5B1%5D%5Bfvd%5D=strains-genus-1) to retreive the strains you are looking for. You can then download the result as CSV (button in top right corner) and use the BacDive-IDs to query the API. Hope this helps.

Cheers,
Julia
